site_name: Terraveil Journal
site_url: https://mgrayd.github.io/DnD-Terraveil/

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: slate
      primary: red
      accent: orange

use_directory_urls: true

nav:
  - Home: index.md
  - Characters:
    - Silas Corvin: 
      - Overview: characters/silas/index.md
      - Stats: characters/silas/stats.md
  - Campaigns:
    - Campaign: campaigns/index.md
    - Session 0: campaigns/Session-0.md
    - Session 1: campaigns/Session-1.md
  - Locations:
    - Indexed Locations: locations/index.md
  - NPCs:
    - Indexed NPCs: npcs/index.md

markdown_extensions:
  - tables
  - admonition
  - md_in_html
  - attr_list
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - toc:
      permalink: true
plugins:
  - search
extra_javascript:
  - https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js
  - https://cdn.jsdelivr.net/npm/@fullcalendar/google-calendar@6.1.8/index.global.min.js
extra_css:
  - https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.css
  - assets/custom.css